typography_spectrum: 0.5223289439454675
color:
  brandColors: []
  brandStrength: 0.625
  lightness: 0.030304316664114594
  saturation: 0.9764935923740268
  rhythmicContrast: 0.590932322666049
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5877920067869127
analytics:
  google: null
  facebook: null
  twitter: null
name: Digital Productivity Consultant
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'http://fundnet.ca'
    type: external
favicon: null
title: Jonathan Hunt Digital Productivity Consultant
purpose: []
